apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boke
  namespace: hugo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: blog.bealzhao.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boke
                port:
                  number: 9090
